# Generated by Django 5.2.6 on 2025-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=256, verbose_name='Пароль')),
                ('status_user', models.BooleanField(default=0, verbose_name='Статус пользователя')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Дата входа')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Библиотекарь',
                'verbose_name_plural': 'Библиотекари',
            },
        ),
    ]
