# Generated by Django 5.2.5 on 2025-09-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookobj',
            name='current_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Текущая цена за день'),
        ),
        migrations.AlterField(
            model_name='bookobj',
            name='return_order',
            field=models.ManyToManyField(to='booklib.returnb', verbose_name='Книги возврата'),
        ),
    ]
