# Generated by Django 5.2.5 on 2025-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='quantity_books',
            field=models.PositiveIntegerField(default=0, verbose_name='Выданные книги'),
        ),
    ]
