# Generated by Django 5.2.5 on 2025-09-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookobj',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booklib.book', verbose_name='Книга'),
        ),
    ]
