# Generated by Django 5.2.6 on 2025-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0002_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Общий рейтинг'),
        ),
    ]
