# Generated by Django 5.2.5 on 2025-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0002_person_quantity_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='quantity_books',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Выданные книги'),
        ),
    ]
