# Generated by Django 5.2.5 on 2025-09-02 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0002_alter_bookobj_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name_genre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Введите только буквы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Жанр'),
        ),
    ]
