# Generated by Django 5.2.6 on 2025-09-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0003_alter_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mark',
        ),
    ]
