# Generated by Django 5.2.5 on 2025-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0003_alter_person_quantity_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='quantity_books',
            field=models.PositiveIntegerField(default=0, verbose_name='Выданные книги'),
        ),
    ]
