# Generated by Django 5.2.5 on 2025-08-30 19:05

import booklib.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0004_alter_person_quantity_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, validators=[booklib.validators.get_name], verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, validators=[booklib.validators.get_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, validators=[booklib.validators.get_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[booklib.validators.get_name], verbose_name='Отчество'),
        ),
    ]
