# Generated by Django 5.2.5 on 2025-08-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0007_alter_person_first_name_alter_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
