# Generated by Django 5.2.5 on 2025-08-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0009_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
