# Generated by Django 5.2.5 on 2025-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0011_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photo_author/', verbose_name='Фото авторов'),
        ),
        migrations.AlterField(
            model_name='fotoregistr',
            name='photo_book',
            field=models.ImageField(upload_to='photo_book/', verbose_name='Фото обложки'),
        ),
        migrations.AlterField(
            model_name='fotostatus',
            name='photo_status',
            field=models.ImageField(blank=True, null=True, upload_to='photo_status/', verbose_name='Фото состояния книги'),
        ),
    ]
